# Default configuration
PARSE_APP_ID = 'cTMwjWCB2ijqCB0ZIad5URdKgJx56SQKOXBKxhoP'
PARSE_RESTAPI_KEY = 'jKDOEVAa5me98CoiKV0Dllx1yFDB789b4e0nTss3'
AWS_ACCESS_KEY = 'AKIAIMY4GPPWHJ3MGCPA'
AWS_SECRET = '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'
S3_BUCKET_NAME_PROFILEPICS = 'favor8-pp-darkhorse'